export const USER_API_END_POINT = "https://carrer-search.onrender.com/api/v1/user";

export const categories = [
  "FrontEnd Developer",
  "Backend Developer",
  "FullStack Developer",
  "Mobile App Developer",
  "Web Developer",
  "Software Engineer",
  "DevOps Engineer",
  "Data Scientist",
  "Data Analyst",
  "Machine Learning Engineer",
  "AI Specialist",
  "Database Administrator",
  "Cloud Engineer",
  "Cybersecurity Specialist",
  "Network Engineer",
  "Systems Administrator",
  "IT Support Specialist",
  "UI/UX Designer",
  "Product Designer",
  "Graphic Designer",
  "Technical Writer",
  "Content Writer",
  "Copywriter",
  "SEO Specialist",
  "Digital Marketing Specialist",
  "Social Media Manager",
  "Content Strategist",
  "Email Marketing Specialist",
  "Product Manager",
  "Product Owner",
  "CRM Specialist",
  "Solutions Architect",
  "Blockchain Developer",
  "Smart Contract Developer",
  "Artificial Intelligence Engineer",
  "Augmented Reality Developer",
  "Virtual Reality Developer",
  "Embedded Systems Engineer",
  "Firmware Engineer",
  "IT Consultant",
  "Business Analyst",
  "Quality Assurance Engineer",
  "Software Tester",
  "Project Manager",
  "Scrum Master",
  "Agile Coach",
  "Marketing Manager",
  "Brand Manager",
  "Public Relations Specialist",
  "Market Research Analyst",
];
